baseURL = 'https://thelio.carlboettiger.info/files/cboettig/quarto-hugo-material-dashboard/public/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'material-kit5'

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true  # Enable user to embed HTML snippets in Markdown content.
    hardwraps = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = false
  [markup.highlight]
    # one of: https://xyproto.github.io/splash/docs/ 
    style = "github"